### ISSUE TITLE
Does not work on colab

### ISSUE THREAD

**Issue by jimhavrilla** [WittmannF/sort-google-scholar#15]
Hello,

I'd love to incorporate this in a project I'm working on.

On colab you need to `pip install selenium` to make it work, and then `chromedriver` does not succeed, even after grabbing the binary and adding to `$PATH` in Colab.  Would be great if this worked on colab as is, or could work out of the box on CMD line.  Could be an amazing tool for the academic field.

I understand if you're no longer working on this though.

Thanks.

**Comment by WittmannF** [comment]
Hey @jimhavrilla ! I just tested here and it is working on colab: https://colab.research.google.com/github/WittmannF/sort-google-scholar/blob/master/Test_sortgs_py_on_Colab.ipynb

Selenium is actually optional and indeed does not work on Colab. However, most of times it will not be necessary, unless you use it too much (then google starts asking for captchas and that's why we would use selenium to handle it).

**Comment by jimhavrilla** [comment]
I found an alternative but good to know, maybe can still incorporate if there's time
