### ISSUE TITLE
Can't run the code on Colab

### ISSUE THREAD

**Issue by mariopaolucci** [WittmannF/sort-google-scholar#9]
Not sure what happened, but I get an error when running on Colab:

```
No success. The following error was raised:
local variable 'Options' referenced before assignment
Loading next 20 results
```

I don't have enough experience with this, but it could be just that https://github.com/WittmannF/sort-google-scholar/blob/6e57704d63086fdbc4b46bcf895c53007771ff47/sortgs.py#L127 should be inside the *try* above:
https://github.com/WittmannF/sort-google-scholar/blob/6e57704d63086fdbc4b46bcf895c53007771ff47/sortgs.py#L118-L124

**Comment by WittmannF** [comment]
Hello @mariopaolucci ! This error is happening because you got the robot checking problem and SortGS is trying to handle it using Selenium, however, selenium is not compatible with Google Colab since it requires a GUI in order to emulate Google Chrome. Try restarting Google Colab or running in your machine.

**Comment by WittmannF** [comment]
If you still need help I reopen it
